# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a758e60a8cc65710f9367f73b5b6190c19f67758c52e0e290fac659bcd5561131192178b956c2f632e8a62d42be74b74abbe1425853d7dccf280d1b03f1a087

test:
  secret_key_base: da2b552bb4f7595099faf65ef07d83441891ddb652f56d373848c2757174830c7dad8cd2c49493a27189fd0687e17a633f12e552c2d56a3ccca9afb07b440312

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"]
